#----------------------------------------------------------------------------
# https://home-assistant.io/components/logger/
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
#----------------------------------------------------------------------------

  default: warn
  logs:
#    # Added to remove some log records at startup
#    homeassistant.components.media_player.squeezebox: fatal
#    homeassistant.components.sensor.mold_indicator: fatal
#    homeassistant.components.sensor: error
#    netdisco.ssdp: error


    # Added to remove:
    # 2019-12-30 22:39:45 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ClientConnectorError'>
    homeassistant.components.squeezebox.media_player: fatal

    # 2019-12-30 22:40:19 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.yamaha_receiver_zone_2 is taking over 10 seconds
    # homeassistant.helpers.entity: error

    # 2019-12-30 22:56:49 WARNING (SyncWorker_8) [homeassistant.components.waze_travel_time.sensor] Error on retrieving data: empty response
    homeassistant.components.waze_travel_time.sensor: error

    aioharmony.hubconnector: fatal
    # 2019-12-31 07:17:22 ERROR (MainThread) [aioharmony.hubconnector] 192.168.1.247: Exception on post: Connection timeout to host http://192.168.1.247:8088/
    # 2019-12-31 07:17:22 ERROR (MainThread) [aioharmony.hubconnector] 192.168.1.247: Unable to retrieve HUB id
    # 2019-12-31 07:22:31 ERROR (MainThread) [aioharmony.hubconnector] 192.168.1.247: Connection timed out for hub 12135421

    # Added to remove:
    # 2020-08-23 11:42:34 WARNING (MainThread) [homeassistant.components.automation.camera_1_image_when_person_detected_and_camera_mode_info] Camera 1 Image when person detected and camera mode Info: Already running
#    homeassistant.components.automation.camera_1_image_when_person_detected_and_camera_mode_day: error
#    homeassistant.components.automation.camera_2_image_when_person_detected_and_camera_mode_day: error
#    homeassistant.components.automation.camera_1_image_when_person_detected_and_camera_mode_away: error
#    homeassistant.components.automation.camera_2_image_when_person_detected_and_camera_mode_away: error

    # 2020-08-26 05:20:39 WARNING (MainThread) [homeassistant.components.automation.camera_1_image_processing_mode_warning] Camera 1 Image processing mode Warning: Already running
#    homeassistant.components.automation.camera_1_image_processing_mode_away: error
#    homeassistant.components.automation.camera_2_image_processing_mode_away: error


    # 2020-10-07 20:21:33 WARNING (MainThread) [homeassistant.components.automation.camera_1_folder_watcher_activated] Camera 1 Folder Watcher activated: Already running
    homeassistant.components.automation.camera_1_folder_watcher_activated: error
    homeassistant.components.automation.camera_2_folder_watcher_activated: error
    homeassistant.components.automation.camera_3_folder_watcher_activated: error

    # 2021-02-12 11:15:14 ERROR (SyncWorker_5) [rxv] Failed to fetch http://192.168.1.24:80/YamahaRemoteControl/desc.xml
    rxv: fatal

    # 2021-02-12 11:15:14 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up yamaha platform for media_player
    homeassistant.components.media_player: fatal

    # 2021-02-12 11:15:28 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ states.media_player.yamaha_receiver.attributes.volume_level * 100}}")
    homeassistant.helpers.event: fatal

    # 2021-02-12 11:15:28 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ states.media_player.yamaha_receiver.attributes.volume_level * 100}}")' for attribute '_state' in entity 'sensor.yamaha_volume_level'
    homeassistant.components.template.template_entity: fatal

    # 2021-02-19 05:54:31 WARNING (SyncWorker_45) [homeassistant.components.local_file.camera] Could not read camera Camera 3 Latest person away image from file: /media/warning/camera_3_1.jpg
    homeassistant.components.local_file.camera: error

    # 2021-02-19 09:00:55 WARNING (SyncWorker_28) [homeassistant.components.xiaomi_miio.vacuum] Got exception while fetching the state: Unable to discover the device 192.168.1.25
    homeassistant.components.xiaomi_miio.vacuum: error

    # 2021-02-19 13:21:22 ERROR (MainThread) [homeassistant.helpers.condition] Error during template condition: UndefinedError: 'dict object' has no attribute 'last_changed'
    homeassistant.helpers.condition: fatal

    # 2021-02-20 08:03:40 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.yamaha_receiver fails
    # 2021-02-20 08:03:40 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.yamaha_receiver_zone_2 fails
    homeassistant.helpers.entity: fatal

    # 2021-05-06 18:19:39 ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `mv -f {{source_file}} {{dest_file}}`, return code: 1
    homeassistant.components.shell_command: fatal
